FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
COPY model.py ./
COPY main.py ./
COPY modelv1.pth ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "main.py"]