services:
  flaskbattery:
    container_name: flaskbattery
    build:
      context: .
      dockerfile: dockerfile
    restart: always

  nginxbattery:
    container_name: nginxbattery
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flaskbattery
      - reactbattery

  reactbattery:
    container_name: reactbattery
    build:
      context: ./battery-website
      dockerfile: dockerfile
    # ports:
    #   - "80:80"
    # depends_on:
    #   - nginxbattery
    restart: always